# set the base image
# creating a build alias to refer to later.
# node is used to built the html and js files
# these will then be served by nginx
FROM node:alpine as build
# set working directory
WORKDIR /app
# copy everything to /app directory for prod
COPY . /app
# add the node_modules folder to $PATH
ENV PATH /app/node_modules/.bin:$PATH
# install dependencies
RUN yarn
# run a builld
RUN yarn build
# the base image for this is an alpine based nginx image to serve our prod app
FROM nginx:alpine
# copy the build folder from react to the root of nginx
# note we are using the alias from earlier
COPY --from=build /app/build /usr/share/nginx/html
# expose port 80
EXPOSE 80
# start nginx
CMD ["nginx", "-g", "daemon off;"]
